@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldHJvdmVuZ2luZWVyQGdtYWlsLmNvbSIsIl9pZCI6IjVmOWQ1MjEyYmVkY2FkMWI2NGVlZTY2ZiIsImV4cCI6MTYwOTQ5ODkwOCwiaWF0IjoxNjA0MzE0OTA4fQ.6ebJvyFEZdojUjVxJ9G0oO92-j5WSr-PIozDk9Z9maA

POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{token}}

mutation Create($name:String){
  createResource(name:$name){
    _id
    name
  }
}

{"name": "test1"}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{token}}

query{
  resources{
    _id
    name
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{token}}

query GetResource($_id: String){
  resource(_id: $_id){
    _id
    name
    created
    tranches{
      amount
      date
      payer{
        name
      }
    }
    waste{
      date
      user{
        email
      }
      cashback
      moneyback
      goal
      amount
    }
    cashWaste{
      date
      user{
        email
      }
      goal
      amount
    }
    creator{
      email
    }
  }
}

{"_id":"5fa451e09374e639e43ca7be"}