@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldHJvdmVuZ2luZWVyQGdtYWlsLmNvbSIsIl9pZCI6IjVmOWQ1MjEyYmVkY2FkMWI2NGVlZTY2ZiIsImV4cCI6MTYxMDM1MzA0OCwiaWF0IjoxNjA1MTY5MDQ4fQ.rjzYch8G2RwMDtI0mtwIkoBGDmdXXdK2oobvUXVbEPU

POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{$dotenv TOKEN}}

mutation CreateTranche($amount:Int, $payer: String, $date: String, $resource: TrancheResourceInputType){
  createTranche(amount:$amount, payer: $payer, date: $date, resource: $resource){
    _id
    amount
    resource{
      _id
      name
    }
    payer{
      name
    }
    date
  }
}

{"amount":2000, "date":"2020-11-06T11:43:05.277Z", "resource":{"_id":"5fa548aac49a0303a0f937e8", "name":"123"}}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{$dotenv TOKEN}}

mutation UpdateTranche($_id: String, $amount:Int, $payer: TranchePayerInputType, $date: String, $resource: TrancheResourceInputType){
  updateTranche(_id: $_id, amount:$amount, payer: $payer, date: $date, resource: $resource){
    _id
    amount
    resource{
      _id
      name
    }
    payer{
      name
    }
    date
  }
}

{"_id":"5fbc00182236681a6c65eaa5","amount":5000, "resource":{"_id":"5fad2935e7e2ad0be0e2eb92", "name":"Вентиляция шкафов"}}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{$dotenv TOKEN}}

mutation RemoveTranche($_id: String){
  deleteTranche(_id: $_id)
}

{"_id":"5fad7febdfef541e24f7490c"}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{$dotenv TOKEN}}

query{
    tranches{
        _id
        amount
        payer{
          name
        }
        date
    }
}

