@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldHJvdmVuZ2luZWVyQGdtYWlsLmNvbSIsIl9pZCI6IjVmOWQ1MjEyYmVkY2FkMWI2NGVlZTY2ZiIsImV4cCI6MTYwOTQ5ODkwOCwiaWF0IjoxNjA0MzE0OTA4fQ.6ebJvyFEZdojUjVxJ9G0oO92-j5WSr-PIozDk9Z9maA

POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{$dotenv TOKEN}}

query GetUser($_id:String){
  user(_id:$_id){
    _id
    email
  }
}

{"_id": "5f9d5212bedcad1b64eee66f"}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
# Authorization: Token {{token}}

mutation Login($email: String!, $password: String!){
  login(email: $email, password: $password){
    _id
    token
  }
}

###
POST http://localhost:3000/login
Content-Type: application/json

{"email": "petrovengineer@gmail.com", "password": "1212"}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{$dotenv TOKEN}}

query {
  auth{
    _id
    email
  }
}