@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldHJvdmVuZ2luZWVyQGdtYWlsLmNvbSIsIl9pZCI6IjVmOWQ1MjEyYmVkY2FkMWI2NGVlZTY2ZiIsImV4cCI6MTYwOTQ5ODkwOCwiaWF0IjoxNjA0MzE0OTA4fQ.6ebJvyFEZdojUjVxJ9G0oO92-j5WSr-PIozDk9Z9maA

POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{token}}

query{
    wastes{
        _id
        goal
        user{
            email
        }
    }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Token {{token}}

mutation CreateWaste($goal: String, $user: String, $date: String, $moneyback: Int, $cashback: Int){
    createWaste(goal: $goal, user: $user, date: $date, moneyback: $moneyback, cashback: $cashback){
        _id
        goal
        user{
            email
        }
    }
}

{"goal":"Test goal", "user":"5f9d5212bedcad1b64eee66f", "moneyback": 1000, "cashback": 3000}
